---
- name: Uninstall k3s
  hosts: all
  become: yes
  
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
  
  tasks:
    - name: Uninstall k3s
      include_tasks: roles/k3s/tasks/uninstall.yml
